on: push
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: 'checkout'
        uses: actions/checkout@v3
      - name: 'build and deploy'
        uses: shalzz/zola-deploy-action@v0.17.2
        env:
          PAGES_BRANCH: gh-pages
          #BUILD_DIR: .
          TOKEN: ${{ secrets.TOKEN }}
          REPOSITORY: tyml-org/tyml-lang.org